### ISSUE TITLE
小細節改善

### ISSUE THREAD

**Issue by LittleWhiteYA** [xxhomey19/PPAV#15]
- [x] PPAV 輸入轉大寫 toUpperCase()
- [x] PPAV 輸出網址上面多加一行空白，避免有些手機不能直接點連結
- [x] 搜尋女優，最多隨機顯示 5 部
- [x] 回傳資訊加上使用 #、@、% 使用教學
- [x] #、@、% 如果後面有空白要處理

**Comment by xxhomey19** [comment]
都改好啦
