### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by LittleWhiteYA** [xxhomey19/PPAV#22]
- [ ] Server 針對 User request 超過一定時間要停止
- [ ] 嘗試把 sendAPI 也回傳到 response，可以進行測試
- [x] 訂閱功能（每日新片）
- [x] Update film_info.json (Python)
- [x] 存取 User log
- [x] callback 嘗試改成 promise 方式
- [x]  針對訂閱功能，大量送出要想辦法寫成 test 檔測試
- [x]  Server log 檔

**Comment by xxhomey19** [comment]
@LittleWhiteYA 
Server 針對 User request 超過一定時間要停止
這個啥時會遇到啊

**Comment by LittleWhiteYA** [comment]
@xxhomey19 我原本是想說這樣可以避免有例外地輸入，導致 Server 產生 Error 卡住吧0.0

**Comment by xxhomey19** [comment]
@LittleWhiteYA 
訂閱功能我先寫紀錄ID
剩下db的部分就交給你啦～
